[[language]]
name = "python"
language-servers = ["ruff", "pylsp"]
auto-format = true

[language-server.pylsp.config.pylsp.plugins]
black.enabled = true

[[grammar]]
name = "odin"
source.path = "C:/Users/navez/AppData/Roaming/helix/tree-sitter-odin"

[[language]]
name = "cpp"
auto-format = true
formatter = { command = "clang-format"}
indent = { tab-width = 2, unit = "  " }
